---

- name: Ping server
  ping:

- name: Set Webmin repository
  apt_repository: 
    repo: 'deb http://download.webmin.com/download/repository sarge contrib' 
    state: present 
    update_cache: yes

- name: Set Webmin repository key
  apt_key: 
    url: http://www.webmin.com/jcameron-key.asc 
    state: present

- name: Install apt-transport-https 
  apt: 
    pkg: "{{ item.pkg }}" 
    state: latest 
    update_cache: yes
  with_items:
    - { pkg: apt-transport-https }
    - { pkg: webmin }

- name: Change Webmin conf file
  replace: 
    dest: "{{ item.dest }}" 
    regexp: "{{ item.regexp }}" 
    replace: "{{ item.replace }}"
  with_items:
    - { dest: "/etc/webmin/miniserv.conf", regexp: "^listen=.*$", replace: "listen={{ webminPort }}" }
    - { dest: "/etc/webmin/miniserv.conf", regexp: "^port=.*$", replace: "port={{ webminPort }}" }
    - { dest: "/etc/webmin/miniserv.conf", regexp: "^ssl=.*$", replace: "ssl={{ webminSSL }}" }
    - { dest: "/etc/webmin/miniserv.conf", regexp: "^preroot=.*$", replace: "preroot={{ webminTheme }}" }
    - { dest: "/etc/webmin/config", regexp: "^theme=.*$", replace: "theme={{ webminTheme }}" }
  notify: Restart Webmin


- block:
  - name: Download openvpn module
    get_url:
      url: http://www.openit.it/downloads/OpenVPNadmin/openvpn-2.6.wbm.gz
      dest: /usr/share/webmin/openvpn-2.6.wbm.gz
  #- name: Copy openvpn module
  #  copy:
  #    src: /root/openvpn-2.6.wbm.gz
  #    dest: /usr/share/webmin/module-archives/openvpn-2.6.wbm.gz
  - name: Install openvpn module
    command:
      /usr/share/webmin/./install-module.pl /usr/share/webmin/./openvpn-2.6.wbm.gz
    notify: Restart Webmin
  when: webminInstallOpenvpn == 'yes'


